version: '3.3'

services:
      dev:
        container_name: qr-server
        image: qr_server_image
        build:
          context: .
          dockerfile: ./Dockerfile
        command: npm start
        ports:
          - 5000:5000
        env_file:
          - ./.env
        restart: unless-stopped